# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
#:schema https://yazi-rs.github.io/schemas/yazi.json

[opener]
append_edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
  { run = "code %*", orphan = true, desc = "code", for = "unix" },
  { run = "code -w %*", block = true, desc = "code (block)", for = "unix" },
]
append_open = [
  { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
append_reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
append_extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
  { run = "ya pub extract --list %*", desc = "Extract here", for = "windows" },
]
append_play = [
  { run = "mpv %s", orphan = true, for = "unix", desc = "Play with MPV" },
  { run = "amberol %s", orphan = true, for = "unix", desc = "Play music with amberol" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[plugin]
prepend_previewers = [
  { mime = "audio/mpegurl", run = "zeditor" },  # ignore .m3u files
  { mime = "audio/*", run = "preview-audio" },
  { url = "**/.git/", run = "preview-git" },
]
prepend_preloaders = [
  { mime = "audio/mpegurl", run = "zeditor" },  # ignore .m3u files
  { mime = "audio/*", run = "preview-audio" },
]
